title: mojobojo
permalink: /blog/:year/:month/:day/:title
pygments: true
url: "imaip.github.io"              # your host, for absolute URL
github_username:  wbwangk

# Build settings
markdown: kramdown
permalink: pretty
